[test]
# Disable parallel test execution to prevent test interference
# This ensures beforeEach hooks run properly before each test
concurrency = 1
# Add timeout for hanging tests (5 minutes for comprehensive MCP tests)
timeout = 300000