blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/ktnyt/codebuddy#readme
    about: Please check the README first for usage instructions
  - name: Discussions
    url: https://github.com/ktnyt/codebuddy/discussions
    about: For general discussions and help from the community